//! Component description and registration system.
//!
//! This module implements the component registry pattern that allows Vector to:
//! - Discover all available components at compile time
//! - Generate schemas for configuration validation
//! - Produce documentation for the vector.dev website
//!
//! # The Registration Pattern
//!
//! Vector uses the `inventory` crate to build a compile-time registry of all components.
//! This works by combining two features:
//!
//! **1. The `inventory::submit!` macro:**
//!
//! Every component file contains:
//! ```ignore
//! inventory::submit! {
//!     SourceDescription::new::<FileConfig>(
//!         "file",
//!         "file",
//!         "file",
//!         "Read from files.",
//!     )
//! }
//! ```
//!
//! Each submitted `ComponentDescription<SourceComponent>` is collected by
//! the `inventory` crate. At compile time, it:
//! - Collects all submissions across the crate graph
//! - Builds a global registry accessible at runtime
//! - Zero runtime overhead (all work done at compile time)
//!
//! **2. The `inventory::collect!` macro:**
//!
//! In `component/mod.rs`, we declare:
//! ```ignore
//! inventory::collect!(SourceDescription);
//! ```
//!
//! This enables `inventory::iter::<SourceDescription>()` to iterate over all
//! sources that submitted themselves.
//!
//! # Why This Pattern?
//!
//! **Alternative 1: Manual registry**
//! ```ignore
//! // In sources/mod.rs
//! pub fn all_sources() -> Vec<&'static str> {
//!     vec!["file", "http", "kafka", ...]  // Must update manually!
//! }
//! ```
//!
//! Problems:
//! - Easy to forget to add new sources
//! - Doesn't work across crate boundaries
//! - Can't discover components from feature-flagged code
//!
//! **Alternative 2: Reflection**
//!
//! Rust doesn't have runtime reflection (by design). We can't iterate over
//! all types implementing `SourceConfig`.
//!
//! **The `inventory` solution:**
//! - Compile-time discovery (no runtime overhead)
//! - Works across crates (each crate submits independently)
//! - Respects feature flags (only compiled components are registered)
//!
//! # ComponentDescription Structure
//!
//! Each description captures:
//!
//! ```ignore
//! pub struct ComponentDescription<T: ComponentMarker> {
//!     component_name: &'static str,   // "file" (unique identifier)
//!     description: &'static str,       // "Read from files." (docs)
//!     label: &'static str,             // "File" (human-readable name)
//!     logical_name: &'static str,      // "file" (used in error messages)
//!     example_value: fn() -> Value,    // Default config example
//!     config: ConfigurableRef,         // Schema generation reference
//! }
//! ```
//!
//! **component_name vs logical_name:**
//!
//! Usually the same, but can differ:
//! - `component_name`: Used in `type: "..."` field (must match typetag)
//! - `logical_name`: Used in error messages (can be more user-friendly)
//!
//! For example, the `docker` source might have:
//! - `component_name`: "docker_logs"
//! - `logical_name`: "docker"
//!
//! # Schema Generation Flow
//!
//! When generating JSON Schema for validation:
//!
//! 1. `ComponentDescription::generate_schemas()` is called
//! 2. It iterates over all registered components via `inventory::iter()`
//! 3. For each component, `generate_schema()` creates a variant schema
//! 4. Variants are combined into a `oneOf` schema
//!
//! The generated schema looks like:
//! ```json
//! {
//!   "oneOf": [
//!     {
//!       "type": "object",
//!       "properties": {
//!         "type": { "const": "file" },
//!         "include": { "type": "array" },
//!         ...
//!       }
//!     },
//!     {
//!       "type": "object",
//!       "properties": {
//!         "type": { "const": "http" },
//!         "address": { "type": "string" },
//!         ...
//!       }
//!     },
//!     ...
//!   ]
//! }
//! ```
//!
//! This allows the config parser to validate that:
//! - `type` field matches a known component
//! - Remaining fields match that component's schema
//!
//! # Example Config Generation
//!
//! The `example_value` function generates default configs for documentation:
//!
//! ```ignore
//! impl GenerateConfig for FileConfig {
//!     fn generate_config() -> toml::Value {
//!         toml::Value::try_from(r#"
//!             [sources.file]
//!             type = "file"
//!             include = ["/var/log/*.log"]
//!         "#).unwrap()
//!     }
//! }
//! ```
//!
//! These examples appear in:
//! - vector.dev component documentation
//! - Default configs generated by `vector generate`
//! - Test fixtures
//!
//! # Phantom Types for Type Safety
//!
//! The `ComponentMarker` trait and its implementations provide type safety:
//!
//! ```ignore
//! pub trait ComponentMarker: Sized {}
//! pub struct SourceComponent;
//! impl ComponentMarker for SourceComponent {}
//!
//! pub type SourceDescription = ComponentDescription<SourceComponent>;
//! ```
//!
//! This ensures:
//! - `SourceDescription` can only describe sources
//! - `SinkDescription` can only describe sinks
//! - Can't accidentally mix them up
//!
//! # Sorted Output
//!
//! The `types()` method returns components in sorted order:
//!
//! ```ignore
//! pub fn types() -> Vec<&'static str> {
//!     let mut types: Vec<_> = inventory::iter::<Self>()
//!         .map(|desc| desc.component_name)
//!         .collect();
//!     types.sort_unstable();
//!     types
//! }
//! ```
//!
//! Sorting ensures:
//! - Deterministic output (same order every run)
//! - Alphabetical listing in documentation
//! - Consistent error messages
//!
//! # Custom Attributes for Documentation
//!
//! Descriptions include custom attributes for the website:
//!
//! ```ignore
//! variant_metadata.add_custom_attribute(CustomAttribute::kv(
//!     constants::DOCS_META_HUMAN_NAME,
//!     self.label,
//! ));
//! ```
//!
//! These attributes are extracted by the documentation generator to produce
//! the component reference pages on vector.dev.

use std::{cell::RefCell, marker::PhantomData};

use snafu::Snafu;
use toml::Value;
use vector_config_common::{attributes::CustomAttribute, constants};

use super::{ComponentMarker, GenerateConfig};
use crate::{
    Configurable, ConfigurableRef, GenerateError, Metadata, schema,
    schema::{SchemaGenerator, SchemaObject},
};

#[derive(Debug, Snafu, Clone, PartialEq, Eq)]
pub enum ExampleError {
    #[snafu(display("component '{}' does not exist", component_name))]
    DoesNotExist { component_name: String },
}

/// Description of a component.
pub struct ComponentDescription<T: ComponentMarker + Sized> {
    component_name: &'static str,
    description: &'static str,
    label: &'static str,
    logical_name: &'static str,
    example_value: fn() -> Value,
    config: ConfigurableRef,
    _component_type: PhantomData<T>,
}

impl<T> ComponentDescription<T>
where
    T: ComponentMarker + Sized + 'static,
    inventory::iter<ComponentDescription<T>>:
        std::iter::IntoIterator<Item = &'static ComponentDescription<T>>,
{
    /// Creates a new `ComponentDescription`.
    ///
    /// This creates a component description for a component identified both by the given component
    /// type `T` and the component name. As such, if `T` is `SourceComponent`, and the name is
    /// `stdin`, you would say that the component is a "source called `stdin`".
    ///
    /// The type parameter `C` must be the component's configuration type that implements
    /// `Configurable` and `GenerateConfig`.
    pub const fn new<C: GenerateConfig + Configurable + 'static>(
        component_name: &'static str,
        label: &'static str,
        logical_name: &'static str,
        description: &'static str,
    ) -> Self {
        ComponentDescription {
            component_name,
            description,
            label,
            logical_name,
            example_value: C::generate_config,
            config: ConfigurableRef::new::<C>(),
            _component_type: PhantomData,
        }
    }

    /// Generates an example configuration for the component with the given component name.
    ///
    /// ## Errors
    ///
    /// If no component, identified by `T` and the given name, is registered, or if there is an
    /// error generating the example configuration, an error variant will be returned.
    pub fn example(component_name: &str) -> Result<Value, ExampleError> {
        inventory::iter::<ComponentDescription<T>>
            .into_iter()
            .find(|t| t.component_name == component_name)
            .ok_or_else(|| ExampleError::DoesNotExist {
                component_name: component_name.to_owned(),
            })
            .map(|t| (t.example_value)())
    }

    /// Gets a sorted list of all registered components of the given component type.
    pub fn types() -> Vec<&'static str> {
        let mut types = Vec::new();
        for definition in inventory::iter::<ComponentDescription<T>> {
            types.push(definition.component_name);
        }
        types.sort_unstable();
        types
    }

    /// Generate a schema object covering all the descriptions of this type.
    pub fn generate_schemas(
        generator: &RefCell<SchemaGenerator>,
    ) -> Result<SchemaObject, GenerateError> {
        let mut descriptions: Vec<_> = inventory::iter::<Self>.into_iter().collect();
        descriptions.sort_unstable_by_key(|desc| desc.component_name);
        let subschemas: Vec<SchemaObject> = descriptions
            .into_iter()
            .map(|description| description.generate_schema(generator))
            .collect::<Result<_, _>>()?;
        Ok(schema::generate_one_of_schema(&subschemas))
    }

    /// Generate a schema object for this description.
    fn generate_schema(
        &self,
        generator: &RefCell<SchemaGenerator>,
    ) -> Result<SchemaObject, GenerateError> {
        let mut tag_subschema =
            schema::generate_const_string_schema(self.component_name.to_string());
        let variant_tag_metadata = Metadata::with_description(self.description);
        schema::apply_base_metadata(&mut tag_subschema, variant_tag_metadata);

        let tag_schema =
            schema::generate_internal_tagged_variant_schema("type".to_string(), tag_subschema);
        let flattened_subschemas = vec![tag_schema];

        let mut field_metadata = Metadata::default();
        field_metadata.set_transparent();
        let mut subschema =
            schema::get_or_generate_schema(&self.config, generator, Some(field_metadata))?;

        schema::convert_to_flattened_schema(&mut subschema, flattened_subschemas);

        let mut variant_metadata = Metadata::default();
        variant_metadata.set_description(self.description);
        variant_metadata.add_custom_attribute(CustomAttribute::kv(
            constants::DOCS_META_HUMAN_NAME,
            self.label,
        ));
        variant_metadata
            .add_custom_attribute(CustomAttribute::kv("logical_name", self.logical_name));
        schema::apply_base_metadata(&mut subschema, variant_metadata);

        Ok(subschema)
    }
}
